name: publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      publish_to_github:
        type: boolean
        description: "Publish to GitHub Releases"
        required: true
        default: true
      publish_to_npm:
        type: boolean
        description: "Publish to NPM"
        required: true
        default: false

permissions:
  id-token: write # Required for OIDC
  contents: write

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Bundle JSON Schemas
        run: |
          pnpm install
          pnpm run release

      - name: Upload Schemas
        uses: actions/upload-artifact@v4
        with:
          name: schemas
          path: schemas/*
          overwrite: true
          if-no-files-found: error

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "ci: release ${{ github.ref_name }}"
          push: origin HEAD:main

  github-release:
    needs: build
    if: ${{ github.event_name == 'push' || github.event.inputs.publish_to_github == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Schemas
        uses: actions/download-artifact@v4

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          make_latest: true
          files: schemas/*

  npm-publish:
    needs: build
    if: ${{ github.event_name == 'push' || github.event.inputs.publish_to_npm == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Download Schemas
        uses: actions/download-artifact@v4

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: NPM Publish
        run: npm publish --access public --tag latest
